# Generated by Django 5.0.4 on 2024-04-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmPass',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
